Ok, we have satisfied the package linter

diff --git a/packages/debian/libpl/DEBIAN/postinst b/packages/debian/libpl/DEBIAN/postinst
--- a/packages/debian/libpl/DEBIAN/postinst
+++ b/packages/debian/libpl/DEBIAN/postinst
@@ -1,5 +1,8 @@
 #!/bin/bash
 
-ldconfig -p
+set -e
+
+echo "No post-installation tasks required"
 
 exit 0
+
